#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript Numerical_Multiblock/master_Rver.R "$@"
matlab -nodisplay -r "addpath(genpath('.')); master"
